global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'shardeum-network-status-monitor'
    static_configs:
      - targets: ['34.170.114.90:3002'] # the exporter runs on this port
      #- targets: ['localhost:3002'] # for local development
    metrics_path: '/metrics'