global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'shardeum-network-status-monitor'
    static_configs:
      - targets: ['host.docker.internal:3002'] # the exporter runs on this port
    metrics_path: '/metrics'